// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery'], function($) {
    return $('.item').find('h3').on('click', function() {
      if ($(this).hasClass('current')) {
        return $(this).remove('current');
      }
    });
  });

}).call(this);
